project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!**/docs/**"
  output-dir: docs

website:
  title: "A Geospatial Data Science Blog"
  favicon: images/favicon.png

  site-url: "https://sebastianof.github.io/GeoDsBlog/"
  google-analytics: "G-VPPV7D4HSQ"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Sebastiano Ferraris. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/sebastianof/
      - icon: envelope
        href: mailto:sebastiano.ferraris@gmail.com
  navbar:
    right:
      - text: Posts
        menu:
          - text: All posts
            href: posts/all.qmd
          - text: Geospatial Data Science
            href: posts/gds.qmd
          - text: Code development
            href: posts/bp.qmd
          # - text: Blogging
          #   href: posts/index_bl.qmd
          # - text: Algorithms
          #   href: posts/index_al.qmd
      # - text: About
      #   menu:
      - text: About
        menu:
          - text: Blog
            href: about/about.qmd
          - text: Feedback
            href: about/feedback.qmd
          - text: Licence
            href: about/licence.qmd
          - text: CV for humans
            href: about/CV_for_humans/curriculum.pdf
          - text: CV for machines
            href: about/CV_for_machines/curriculum.docx.pdf
      - icon: github
        href: https://github.com/sebastianof/
      - icon: envelope
        href: mailto:sebastiano.ferraris@gmail.com
format:
  html:
    include-in-header:
    - text: |
        <link rel = "shortcut icon" href = "images/favicon.png" />
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    theme: [flatly, theme-light.scss]
      # light: 
      # dark: [flatly, theme-dark.scss]
    css: styles.css
    mainfont: math
