project:
  type: website

website:
  title: "Geospatial data science blog"
  # site-url: ""
  # google-analytics: ""

  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Sebastiano Ferraris. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/sebastianof/
      - icon: envelope
        href: mailto:sebastiano.ferraris@gmail.com

  navbar:
    right:
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: Geospatial Data Science
            href: posts/index_gds.qmd
          - text: Code development
            href: posts/index_bp.qmd
          - text: Blogging
            href: posts/index_bl.qmd
          # - text: Algorithms
          #   href: posts/index_al.qmd
      # - text: About
      #   menu:
      - text: About
        href: about/about.qmd
      #     - text: My CV
      #       href: series-gha.qmd
      #     - text: Publications
      #       href: series-gha.qmd
      #     - text: Open source projects
      #       href: series-gha.qmd

      # - text: Resume
      #   href: https://beatrizmilz.github.io/resume/index.pdf
      # - icon: github
      #   href: https://github.com/SebastianoF/AlgoCorner

format:
  html:
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    theme:
      light: simple
      dark: superhero
    css: styles.css
    mainfont: math
